# Site settings
title: Sdok
description: "Sdok"
baseurl:
url: "https://sdqcdongari.github.io/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: sdqcd
user_title: sdqcd
email: 
twitter_username: 
github_username:  
gplus_username:  
linkedin_public_url:  # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: 
profile_picture: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.facebook.com%2Fsungdeokcouncil%2Fposts&psig=AOvVaw0sA4yBPU9OX3DZR24FZOEu&ust=1591205093165000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCMiliYbT4-kCFQAAAAAdAAAAABAD

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: true

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: github
      url: 
      new_tab: true
      key_trigger: g
    - title: twitter
      url: 
      key_trigger: t
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: 1
    url: 
  - name: 2
    url: 
  - name: 3
    url:  

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
