# Site settings
title: Sdok - QCD
description: "QCD"
baseurl:
url: "https://sdqcd.github.io/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.o'

# User settings
username: QCD
user_title: QCD1
email: hyung5371@naver.com
github_username: https://github.com/SDQCD/SDQCD.github.io/
linkedin_public_url:  # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
profile_picture: http://blogfiles.naver.net/MjAyMDA1MDJfMTkw/MDAxNTg4NDA1NTUyNjAx.HdO5tvaN_VGKKDq93DL3LDl2gsQbYSGpt6foCM6__EIg.eT7w6Nzzaw4JZVz-4Kw6EWz9Y6EsEn09xFKY8oRYEvYg.JPEG.dd0u0bb__/IMG_2674.JPG

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: true

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /home
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: TITLE1
      url: 
      new_tab: true
      key_trigger: g
    - title: TITLE2
      url: 
      key_trigger: t
    - title: TITLE3
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: 
    url: 
  - name: 2
    url: 
  - name: 3
    url:  

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
